### ISSUE TITLE
pretrained resnet152 h5 file

### ISSUE THREAD

**Issue by orchardchang** [cvlab-tohoku/Dense-CoAttention-Network#2]
I only find load_features.ipynb for loading pre-trained features from Faster RCNN, but I cannot find preprocess files to load pre-trained features from resnet 152. 
So, how can I generate h5 files of pre-trained features from resnet 152, if I want to train the model with resnet 152?
Thanks!

**Comment by kienduynguyen** [comment]
Hi @orchardchang ,

For Faster RCNN, we load pre-trained features from files provided in this paper https://github.com/peteanderson80/bottom-up-attention. That's why we need code to move features from tsv files to h5py file which is in load_features.ipynb.

For ResNet-152, we don't use pretrained features but feed the image into pre-trained ResNet during training. So our dataloader provides 2 ways to deal with images. In the first way, you can provide our dataloader the folder of images and set use_h5py=False (you can check it in ./dense_coattn/data/dataset.py). In the second method, you can load the image into h5py first (using ./preprocess/load_img.py) and then feed the h5py file into our dataloader with use_h5py=True. The second method is faster but requires more memory than the first one, however both of them work similarly.

**Comment by orchardchang** [comment]
Thanks for your kind reply!
Your code is really professional and helps me a lot.
