### ISSUE TITLE
How do you predict the answer while you don't use the answer feature for prediction?

### ISSUE THREAD

**Issue by bearcatt** [cvlab-tohoku/Dense-CoAttention-Network#9]
I read your code [here](https://github.com/cvlab-tohoku/Dense-CoAttention-Network/blob/master/answer.py#L36), it seems that you predict a list of scores based barely on the image and question feature, find the index of the largest score, and use this index to find the answer in the answer list. 
However, since you didn't use the answer feature, I think you may predict the same scores even if you shuffle the answer list randomly.

Did I miss something in the code? I will be happy if you can give me an answer :)

**Comment by kienduynguyen** [comment]
Hi @bearcatt ,

Many papers follow the same solution that the list of answers is predefined and we treat the problem as a classification problem. That's a reason we don't use the answer feature.

**Comment by bearcatt** [comment]
@kienduynguyen thanks for your reply. I notice that Equation (16) in your paper uses the answer feature, but it got worse performance on VQA1.0. This is quite strange because the model performs better on an **Answering** task when it actually knows nothing about the exact answers. Can you help me understand this?

**Comment by kienduynguyen** [comment]
Hi @bearcatt ,

When we treat the problem as classification, the answer features are learned in the classification layer (each answer is represented by a vector independently and we put no inductive bias inside those answers). But when we use answer features as features generated by lstm and word2vec, we encode an inductive bias, such as "red" and "white" are close to each other since they are all colors in word2vec. This inductive bias may not be true or have no positive affect.

**Comment by bearcatt** [comment]
@kienduynguyen  I understand. Many thanks to your answers :)
